### PR TITLE
add failing admin party scenario

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by robertkowalski** [comment]
@janl output is:

node1.log says

```
[snip]

2015-07-31 16:59:48.548 [notice] node1@127.0.0.1 <0.320.0> ee8d2ae6bf 127.0.0.1 127.0.0.1:15984 GET / 200 ok 1
2015-07-31 16:59:58.294 [debug] node1@127.0.0.1 <0.245.0> 'GET' /_nodes/_all_docs {1,1} from "127.0.0.1"
Headers: [{'Accept',"*/*"},{'Host',"127.0.0.1:15986"},{'User-Agent',"curl/7.37.1"}]
2015-07-31 16:59:58.294 [debug] node1@127.0.0.1 <0.245.0> OAuth Params: []
2015-07-31 16:59:58.295 [notice] node1@127.0.0.1 <0.245.0> 127.0.0.1 - - GET /_nodes/_all_docs 200
2015-07-31 16:59:58.301 [notice] node1@127.0.0.1 <0.398.0> Setup: [{<<"action">>,<<"enable_cluster">>},{<<"username">>,<<"a">>},{<<"password">>,<<"b">>},{<<"bind_address">>,<<"0.0.0.0">>}]
2015-07-31 16:59:58.301 [notice] node1@127.0.0.1 <0.149.0> config: [admins] a set to -pbkdf2-4388b5c008c4a0289e212b1384b50e909432ada4,6b08b2bb43ff7c23ea19b4f515358a04,10 for reason nil
2015-07-31 16:59:58.303 [notice] node1@127.0.0.1 <0.149.0> config: [httpd] bind_address set to 0.0.0.0 for reason nil
2015-07-31 16:59:58.304 [notice] node1@127.0.0.1 <0.398.0> Enable Cluster: [{bind_address,<<"0.0.0.0">>},{password,<<"b">>},{username,<<"a">>}]
2015-07-31 16:59:58.304 [error] Undefined <0.222.0> Supervisor couch_secondary_services had child httpd started with couch_httpd:start_link() at <0.229.0> exit with reason normal in context child_terminated
2015-07-31 16:59:58.304 [notice] node1@127.0.0.1 <0.398.0> 4ffd20bd2a 127.0.0.1 127.0.0.1:15984 POST /_cluster_setup 201 ok 4
2015-07-31 16:59:58.306 [debug] Undefined <0.222.0> Supervisor couch_secondary_services started couch_httpd:start_link() at pid <0.414.0>
2015-07-31 16:59:58.312 [debug] node1@127.0.0.1 <0.327.0> cache miss for a
2015-07-31 16:59:58.312 [notice] node1@127.0.0.1 <0.327.0> Setup: [{<<"action">>,<<"add_node">>},{<<"username">>,<<"a">>},{<<"password">>,<<"b">>},{<<"host">>,<<"127.0.0.1">>},{<<"port">>,25984}]
2015-07-31 16:59:58.312 [notice] node1@127.0.0.1 <0.327.0> add_node: [{<<"action">>,<<"add_node">>},{<<"username">>,<<"a">>},{<<"password">>,<<"b">>},{<<"host">>,<<"127.0.0.1">>},{<<"port">>,25984}]
2015-07-31 16:59:58.313 [notice] node1@127.0.0.1 <0.327.0> add node: [{port,25984},{host,<<"127.0.0.1">>},{password,<<"b">>},{username,<<"a">>}]
2015-07-31 16:59:58.316 [notice] node1@127.0.0.1 <0.327.0> send_req: {ok,"302",[{"X-CouchDB-Body-Time","0"},{"X-Couch-Request-ID","1f3356f0b7"},{"Server","CouchDB/a150e5d (Erlang OTP/17)"},{"Location","http://127.0.0.1:25984/_utils/session.html?return=%2F_cluster_setup&reason=Name%20or%20password%20is%20incorrect."},{"Date","Fri, 31 Jul 2015 14:59:58 GMT"},{"Content-Type","text/plain; charset=utf-8"},{"Content-Length","67"},{"Cache-Control","must-revalidate"}],"{\"error\":\"unauthorized\",\"reason\":\"Name or password is incorrect.\"}\n"}
2015-07-31 16:59:58.316 [notice] node1@127.0.0.1 <0.327.0> e1e2a9c388 127.0.0.1 127.0.0.1:15984 POST /_cluster_setup 201 ok 6
2015-07-31 16:59:58.321 [debug] node1@127.0.0.1 <0.330.0> cache hit for a
2015-07-31 16:59:58.321 [notice] node1@127.0.0.1 <0.330.0> Setup: [{<<"action">>,<<"enable_cluster">>},{<<"remote_node">>,<<"127.0.0.1">>},{<<"port">>,<<"25984">>},{<<"username">>,<<"a">>},{<<"password">>,<<"b">>},{<<"bind_address">>,<<"0.0.0.0">>}]
2015-07-31 16:59:58.325 [notice] node1@127.0.0.1 <0.330.0> send_req: {ok,"500",[{"X-CouchDB-Body-Time","0"},{"X-Couch-Stack-Hash","1871142869"},{"X-Couch-Request-ID","00d496cd25"},{"Server","CouchDB/a150e5d (Erlang OTP/17)"},{"Date","Fri, 31 Jul 2015 14:59:58 GMT"},{"Content-Type","text/plain; charset=utf-8"},{"Content-Length","61"},{"Cache-Control","must-revalidate"}],"{\"error\":\"unknown_error\",\"reason\":\"badarg\",\"ref\":1871142869}\n"}
2015-07-31 16:59:58.325 [notice] node1@127.0.0.1 <0.330.0> 634b961c50 127.0.0.1 127.0.0.1:15984 POST /_cluster_setup 201 ok 4
2015-07-31 16:59:58.330 [debug] node1@127.0.0.1 <0.415.0> 'GET' /_nodes/_all_docs {1,1} from "127.0.0.1"
Headers: [{'Accept',"*/*"},{'Authorization',"Basic YTpi"},{'Host',"127.0.0.1:15986"},{'User-Agent',"curl/7.37.1"}]
2015-07-31 16:59:58.330 [debug] node1@127.0.0.1 <0.415.0> OAuth Params: []
2015-07-31 16:59:58.330 [notice] node1@127.0.0.1 <0.415.0> 127.0.0.1 - - GET /_nodes/_all_docs 200
2015-07-31 16:59:58.336 [debug] node1@127.0.0.1 <0.328.0> cache hit for a
2015-07-31 16:59:58.336 [debug] node1@127.0.0.1 <0.328.0> httpd 404 error response:
 {"error":"not_found","reason":"Database does not exist."}

[snip]


```

**Comment by robertkowalski** [comment]
looks like a race condition between the supervisor restart and my next request.

i have the same problem with fauxton

**Comment by kxepal** [comment]
Few important lines that were snipped:

```
2015-07-31 18:18:12.350 [error] node1@127.0.0.1 <0.322.0> req_err(1384774233) unknown_error : badarg
    [<<"erlang:binary_to_list/1">>,<<"setup:enable_cluster_http/1 L76">>,<<"setup_httpd:handle_action/2 L63">>,<<"setup_httpd:handle_setup_req/1 L24">>,<<"chttpd:handle_request_int/1 L221">>,<<"mochiweb_http:headers/5 L93">>,<<"proc_lib:init_p_do_apply/3 L239">>]
2015-07-31 18:18:12.350 [error] node1@127.0.0.1 <0.322.0> httpd 500 error response:
 {"error":"unknown_error","reason":"badarg","ref":1384774233}
```

**Comment by robertkowalski** [comment]
are you sure? my pr also contains a patch

**Comment by kxepal** [comment]
@robertkowalski pretty sure. Ran `make clean && make && rm -rf dev/{lib,log} && ./dev/run --with-admin-party-please -n2 --no-join && ./src/setup/test/t-admin-party.sh`

See logs and errors:
https://www.friendpaste.com/5KvlnHXs2UrUt6Ytfo4f2g

**Comment by robertkowalski** [comment]
it works now, after a bug somewhere else was fixed.

**Pull request closed without merging**
